### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by EV71** [rotmoset/gbdk-n#3]
multi bank support?

windows support?

**Comment by andreasjhkarlsson** [comment]
The project should include .bat files for building the library on Windows.

**Comment by Kusefiru** [comment]
Hey! It seems you haven't added support for .bat files yet. 
I can work on it if you're okay with it.

**Comment by andreasjhkarlsson** [comment]
Sure, have fun!

**Comment by andreasjhkarlsson** [comment]
Solved in this [pull request](https://github.com/rotmoset/gbdk-n/pull/9).
